name: ProençaBand
favicon: null
layout_spectrum: 0.99586
typography_spectrum: 0.56736
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bec8d2'
    - '#877f72'
    - '#0f150b'
    - '#605845'
    - '#8ba122'
  brandStrength: 0.8360483681317419
  lightness: 0.1633695417549461
  saturation: 0.32128368760459125
  rhythmicContrast: 0.6817631844896823
purpose: []
